### ISSUE TITLE
The game freezes when I use this

### ISSUE THREAD

**Issue by Lazzil** [IceFreez3r/marketplace-tracker#48]
It freezes as soon as I open the marketplace. When I couldn't get it working with the userscript, I removed that and installed the addon. Neither worked for me.

**Comment by IceFreez3r** [comment]
Do you have other userscripts installed? Especially Daels Collection

**Comment by Lazzil** [comment]
I do, actually. And it seems disabling that has fixed the issue.

Fuck, is it absolutely impossible to use them both together? I can let go of most features, but I really liked the loadout swapper and having prices visible from the inventory.

**Comment by Lazzil** [comment]
Thanks for the update!

The issue I was having has been resolved with the update, but I can't access the settings while I have DaellS scripts going. I can work around this by temporarily disabling his scripts, making changes to the settings, and then re-enabling them, but I thought I should bring this up since it is kinda wonky.
