### ISSUE TITLE
Incorrect selector for cooking preparation tab 

### ISSUE THREAD

**Issue by demcookies** [IceFreez3r/marketplace-tracker#87]
Name for the Cooking preparation tab has changed from "Preparing" to "Preparation" and has broken the tracker selection for the tab.  
https://github.com/IceFreez3r/marketplace-tracker/blob/2adc43d5a083cd084bac755915c9be8bd096d607/modules/cooking.js#L215
Should be changed to ```if (selectedTab === "Preparation") {```

**Comment by IceFreez3r** [comment]
Hey, thx for the report. Will look into fixing it soon

**Comment by IceFreez3r** [comment]
Issue was resolved in #88
